#!/bin/sh
#Set up script for Linux Mint 20.2 Cinnamon Uma.
#I use this to test TR under mint on my shack computer without
#permanently installing it.
#############################################################################
#Steps for w9cf shack computer:
#1. Download Linux mint iso set up disk and copy it on boot media.
#2. Boot and choose the first choice from grub to get a live version.
#3. Click on Network icon to set up wifi network, then download this file 
#4. Pop up a terminal and run this script.
#############################################################################
#
#make temporary file for so2r box udev rule
#
temp1=`mktemp mint.XXXXXX` || exit 1
onexit() {
   rm -f ${temp1}
}
trap onexit EXIT QUIT
#
#install software needed to compile/run trlog, -y answers yes to all questions
#
sudo apt-get -y update
sudo apt-get -y install git
sudo apt-get -y install build-essential
sudo apt-get -y install libusb-1.0-0-dev
sudo apt-get -y install libieee1284-3-dev
sudo apt-get -y install libcurl4-openssl-dev
sudo apt-get -y install libsndfile1-dev
sudo apt-get -y install libasound-dev
sudo apt-get -y install libudev-dev
sudo apt-get -y install xorg-dev
sudo apt-get -y install ncat
sudo apt-get -y install texlive
sudo apt-get -y install xpdf
sudo apt-get -y install xterm
sudo apt-get -y install fpc

# Download the source and make the executables
git clone https://github.com/trlinux/trlinux.git
# Build trlinux
(cd trlinux; make)
#
#set up DosTerm and BigDosTerm
#
cp trlinux/files/Xresources .Xresources
xrdb -merge .Xresources
#
# add group so2rbox
#
sudo addgroup so2rbox
#
#set up udev rule for YCCC SO2R box
#
cat << EOF > ${temp1}
SUBSYSTEM=="usb", ATTRS{idVendor}=="16c0", ATTR{idProduct}=="065e", MODE="0660", GROUP="so2rbox"
EOF
sudo mv ${temp1} /etc/udev/rules.d/50-usb-so2r.rules
sudo chown root.root /etc/udev/rules.d/50-usb-so2r.rules
sudo udevadm control -R
#
#make mint a member of dialout and so2rbox
#
sudo gpasswd -a mint dialout
sudo gpasswd -a mint so2rbox
#
#quick and dirty method to get this terminal to reread groups without
#logging out and in
#
exec sudo su -l mint
export DISPLAY=:0
